"""new_fields

Revision ID: 060c571aa1d6
Revises: aeb1f880b626
Create Date: 2025-06-01 21:39:30.915891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060c571aa1d6'
down_revision = 'aeb1f880b626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('diagnosis', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('medication', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('comorbidities', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('admission_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('ntprobnp', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('kalium', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('natrium', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('kreatinin_gfr', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('harnstoff', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hb', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('kccq', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('initial_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('initial_bp', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bp', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pulse', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('medication_changes', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('kalium_daily', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('natrium_daily', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('kreatinin_gfr_daily', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('harnstoff_daily', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hb_daily', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ntprobnp_daily', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('abschluss_labor', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('current_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discharge_medication', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('kccq_discharge', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('discharge_date', sa.Date(), nullable=True))
        batch_op.alter_column('hospitalization_day',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('voice_sample',
               existing_type=sa.BLOB(),
               nullable=True)
        batch_op.alter_column('nocturnal_cough_sample',
               existing_type=sa.BLOB(),
               nullable=True)
        batch_op.alter_column('breathing_difficulty',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('chest_pain',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('fatigue_level',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sleep_quality',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.alter_column('sleep_quality',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('fatigue_level',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('chest_pain',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('breathing_difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('nocturnal_cough_sample',
               existing_type=sa.BLOB(),
               nullable=False)
        batch_op.alter_column('voice_sample',
               existing_type=sa.BLOB(),
               nullable=False)
        batch_op.alter_column('weight',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('hospitalization_day',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('discharge_date')
        batch_op.drop_column('kccq_discharge')
        batch_op.drop_column('discharge_medication')
        batch_op.drop_column('current_weight')
        batch_op.drop_column('abschluss_labor')
        batch_op.drop_column('ntprobnp_daily')
        batch_op.drop_column('hb_daily')
        batch_op.drop_column('harnstoff_daily')
        batch_op.drop_column('kreatinin_gfr_daily')
        batch_op.drop_column('natrium_daily')
        batch_op.drop_column('kalium_daily')
        batch_op.drop_column('medication_changes')
        batch_op.drop_column('pulse')
        batch_op.drop_column('bp')
        batch_op.drop_column('initial_bp')
        batch_op.drop_column('initial_weight')
        batch_op.drop_column('kccq')
        batch_op.drop_column('hb')
        batch_op.drop_column('harnstoff')
        batch_op.drop_column('kreatinin_gfr')
        batch_op.drop_column('natrium')
        batch_op.drop_column('kalium')
        batch_op.drop_column('ntprobnp')
        batch_op.drop_column('admission_date')
        batch_op.drop_column('comorbidities')
        batch_op.drop_column('medication')
        batch_op.drop_column('diagnosis')
        batch_op.drop_column('height')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
