"""rename fields

Revision ID: 523df25fa2cc
Revises: d91bb323a8c6
Create Date: 2025-06-11 14:29:10.242623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523df25fa2cc'
down_revision = 'd91bb323a8c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_sample_standardized', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('voice_sample_storytelling', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('nocturnal_cough_sample')
        batch_op.drop_column('voice_sample')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_sample', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('nocturnal_cough_sample', sa.BLOB(), nullable=True))
        batch_op.drop_column('voice_sample_storytelling')
        batch_op.drop_column('voice_sample_standardized')

    # ### end Alembic commands ###
