"""delete old ones

Revision ID: a6c8b81fc025
Revises: 060c571aa1d6
Create Date: 2025-06-01 21:43:57.047784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c8b81fc025'
down_revision = '060c571aa1d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.drop_column('breathing_difficulty')
        batch_op.drop_column('sleep_quality')
        batch_op.drop_column('nocturnal_cough_sample')
        batch_op.drop_column('chest_pain')
        batch_op.drop_column('fatigue_level')
        batch_op.drop_column('additional_notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_notes', sa.VARCHAR(length=10000), nullable=True))
        batch_op.add_column(sa.Column('fatigue_level', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('chest_pain', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('nocturnal_cough_sample', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('sleep_quality', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('breathing_difficulty', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
