"""second voice

Revision ID: d91bb323a8c6
Revises: c3cf652ed7da
Create Date: 2025-06-11 14:26:23.865516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91bb323a8c6'
down_revision = 'c3cf652ed7da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nocturnal_cough_sample', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.drop_column('nocturnal_cough_sample')

    # ### end Alembic commands ###
