"""Add voice_sample_vocal field

Revision ID: 49431d80261e
Revises: 8dce47e67574
Create Date: 2025-07-08 20:31:27.486514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49431d80261e'
down_revision = '8dce47e67574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_sample_vocal', sa.LargeBinary(), nullable=True))
        batch_op.alter_column('hospitalization_day',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.alter_column('hospitalization_day',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('voice_sample_vocal')

    # ### end Alembic commands ###
