"""kccq added

Revision ID: a87067c7e0d8
Revises: aac8cc64030b
Create Date: 2025-06-01 22:13:57.444533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87067c7e0d8'
down_revision = 'aac8cc64030b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kccq1a', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq1b', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq1c', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq1d', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq1e', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq1f', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq4', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq5', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq6', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq7', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq8', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq9', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq10', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq11', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq12', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq13', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq14', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq15a', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq15b', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq15c', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq15d', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kccq16', sa.Integer(), nullable=True))
        batch_op.drop_column('kccq_discharge')
        batch_op.drop_column('kccq')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kccq', sa.VARCHAR(length=1000), nullable=True))
        batch_op.add_column(sa.Column('kccq_discharge', sa.VARCHAR(length=1000), nullable=True))
        batch_op.drop_column('kccq16')
        batch_op.drop_column('kccq15d')
        batch_op.drop_column('kccq15c')
        batch_op.drop_column('kccq15b')
        batch_op.drop_column('kccq15a')
        batch_op.drop_column('kccq14')
        batch_op.drop_column('kccq13')
        batch_op.drop_column('kccq12')
        batch_op.drop_column('kccq11')
        batch_op.drop_column('kccq10')
        batch_op.drop_column('kccq9')
        batch_op.drop_column('kccq8')
        batch_op.drop_column('kccq7')
        batch_op.drop_column('kccq6')
        batch_op.drop_column('kccq5')
        batch_op.drop_column('kccq4')
        batch_op.drop_column('kccq3')
        batch_op.drop_column('kccq2')
        batch_op.drop_column('kccq1f')
        batch_op.drop_column('kccq1e')
        batch_op.drop_column('kccq1d')
        batch_op.drop_column('kccq1c')
        batch_op.drop_column('kccq1b')
        batch_op.drop_column('kccq1a')

    # ### end Alembic commands ###
