"""delete systolic

Revision ID: aac8cc64030b
Revises: a6c8b81fc025
Create Date: 2025-06-01 21:44:37.314045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac8cc64030b'
down_revision = 'a6c8b81fc025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.drop_column('diastolic')
        batch_op.drop_column('systolic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('systolic', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('diastolic', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
