"""add estimated_dryweight field

Revision ID: 1d4c39f1c2a6
Revises: aeb3125d473e
Create Date: 2025-07-11 21:37:08.892998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4c39f1c2a6'
down_revision = 'aeb3125d473e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_dryweight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.drop_column('estimated_dryweight')

    # ### end Alembic commands ###
