"""nullable

Revision ID: aeb1f880b626
Revises: dc215af0fc07
Create Date: 2025-05-21 22:03:55.472377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb1f880b626'
down_revision = 'dc215af0fc07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.alter_column('systolic',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('diastolic',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.alter_column('diastolic',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('systolic',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
